backend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-022-024/sausage-store/sausage-backend
    tag: 1.0.1090986
  replicas: 1
  service:
    port: 8080
    targetPort: 8080
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "20"
  startupProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 6

backend-report:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-022-024/sausage-store/backend-report
    tag: latest
  replicas: 1
  service:
    port: 8080
    targetPort: 8080
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: Recreate

frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-022-024/sausage-store/sausage-frontend
    tag: 1.1.3
  replicas: 1
  service:
    port: 80
    targetPort: 8080
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: Recreate
  fqdn: alekseev-roman-022.k8s.praktikum-services.tech
  ingress:
    port: 80
