---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-secrets
# data:
#   SPRING_CLOUD_VAULT_TOKEN: ****************************
# type: Opaque 



apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF5TWkwd01qUTZhemhuZVRWSlNqYz0iCgkJfQoJfQp9
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".dockerconfigjson":"ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF5TWkwd01qUTZhemhuZVRWSlNqYz0iCgkJfQoJfQp9"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2024-02-21T09:33:09Z","name":"docker-config-secret","namespace":"std-022-024","resourceVersion":"1381292378","uid":"6d96b06c-91d6-4417-a7f3-529edd2a3c87"},"type":"kubernetes.io/dockerconfigjson"}
  creationTimestamp: "2024-02-26T06:04:00Z"
  name: docker-config-secret
  #namespace: std-022-024
  resourceVersion: "1393153422"
  uid: efe65655-8b08-4d08-b6b2-10b1eb292dd0
type: kubernetes.io/dockerconfigjson
